# Generated by Django 5.2.2 on 2025-06-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_advisor_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hubspot_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
