# Generated by Django 5.2.2 on 2025-06-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_advisor_ai', '0004_agenttask_ongoinginstruction_taskstep_webhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='summary',
            field=models.TextField(blank=True, help_text='Human-readable summary of the event'),
        ),
    ]
