# Generated by Django 5.2.2 on 2025-06-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_advisor_ai', '0005_webhookevent_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='is_suggestion',
            field=models.BooleanField(default=False, help_text='Whether this task was suggested by AI'),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('waiting_response', 'Waiting for Response'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
    ]
